

//  Created by Romain Mottier
//  Explicit (ERK) counterpart of BrainIHHOFirstOrder.hpp, structured after
//  HeterogeneousEHHOFirstOrder.hpp (the working ERK + elastic/acoustic
//  coupling pattern - NOT BassinEHHOFirstOrder.hpp, whose time-marching loop
//  and erk_coupling_hho_scheme setup were left unfinished/commented out).
//
//  Unlike Heterogeneous's simple half-plane split (bar.y() > 0), material
//  and face classification here follow the mesh's per-polygon material id
//  (mri_dataset/generate_mesh.py, MATERIAL_IDS), same convention as
//  BrainIHHOFirstOrder.hpp.
//
//  TODO before this is physically meaningful (same as the implicit version):
//   - time range, pulse location/frequency and the pixel-to-distance scale
//     are placeholders and must be set once the physical scale of the
//     segmentation mesh (mm/pixel, excitation source) is fixed
//   - bone shear-wave speeds (vs) below are rough literature placeholders
//   - ERK is only conditionally stable (CFL): expect to need a much larger
//     -n (time step count) than the implicit (DIRK) run for the same tf


void BrainEHHOFirstOrder(int argc, char **argv);

void BrainEHHOFirstOrder(int argc, char **argv){

    // ######################################################################
    // ###################################################################### Simulation paramaters
    // ######################################################################

    std::cout << std::endl << bold << red << "   EXPLICIT BRAIN (MRI SEGMENTATION)" << std::endl;
    using RealType = double;
    simulation_data sim_data = preprocessor::process_args(argc, argv);
    sim_data.print_simulation_data();
    timecounter tc, tcit, cpu;
    cpu.tic();

    // ######################################################################
    // ###################################################################### Mesh generation
    // ######################################################################

    tc.tic();
    typedef disk::mesh<RealType, 2, disk::generic_mesh_storage<RealType, 2>>  mesh_type;
    typedef disk::BoundaryConditions<mesh_type, false> e_boundary_type;
    typedef disk::BoundaryConditions<mesh_type, true> a_boundary_type;
    mesh_type msh;

    auto validate_l = [](size_t l) -> size_t {
        if ((0 <= l) && (l < 1) ) {
            return l;
        }
        else {
            std::cout << std::endl << std::endl;
            std::cout << "Warning:: Only few polygonal meshes available.";
            std::cout << std::endl << std::endl;
            return 0;
        }
    };

    size_t l = validate_l(sim_data.m_n_divs);
    polygon_2d_mesh_reader<RealType> mesh_builder;
    std::vector<std::string> mesh_files;

    // TEMPORARY DIAGNOSTIC: uniform mesh (mesh_size=1.0 everywhere, no
    // Distance/Threshold grading, no agglomeration) to check whether the
    // fine/coarse cell-size contrast itself is producing spurious
    // scattering near the skull. Revert to "../meshes/brain.txt" once
    // checked.
    mesh_files.push_back("../meshes/brain_uniform.txt");    // l = 0, generated by mri_dataset/generate_mesh.py

    // Reading the polygonal mesh (same reader/format as the Basin case:
    // build_bassin() is format-generic, it just reads whatever integer
    // material id is stored per polygon)
    mesh_builder.set_poly_mesh_file(mesh_files[l]);
    mesh_builder.build_bassin();
    mesh_builder.move_to_mesh_storage(msh);
    mesh_builder.remove_duplicate_points();

    RealType h = 10;
    for (auto & cell : msh ) {
        auto cell_ind = msh.lookup(cell);
        mesh_type::point_type bar = barycenter(msh, cell);
        RealType h_l = diameter(msh, cell);
        if (h_l < h)
            h = h_l;
    }

    tc.toc();
    std::cout << bold << red << "   MESH GENERATION : ";
    std::cout << tc << " seconds" << reset << std::endl << std::endl;

    // ######################################################################
    // ###################################################################### Time controls
    // ######################################################################

    size_t nt = 10;
    for (unsigned int i = 0; i < sim_data.m_nt_divs; i++) {
        nt = sim_data.m_nt_divs;
    }

    RealType ti = 0.0;
    RealType tf = 0.1;
    RealType dt = (tf-ti)/nt;
    RealType t  = ti;

    // ######################################################################
    // ###################################################################### HHO setting
    // ######################################################################

    // Creating HHO approximation spaces and corresponding linear operator
    size_t cell_k_degree = sim_data.m_k_degree;
    if(sim_data.m_hdg_stabilization_Q)
        cell_k_degree++;

    disk::hho_degree_info hho_di(cell_k_degree,sim_data.m_k_degree);

    // ##################################################
    // ################################################## Material data
    // ##################################################
    //
    // Material ids (assigned in mri_dataset/generate_mesh.py, MATERIAL_IDS):
    //   1 : cortical bone (outer + inner table)   -> elastic
    //   2 : cancellous bone (diploe)               -> elastic
    //   3 : background                             -> acoustic
    //   4 : cerebrospinal fluid (CSF)               -> acoustic
    //   5 : gray matter                             -> acoustic
    //   6 : white matter                            -> acoustic
    //
    // P-wave speeds and densities sourced from wave_speeds_1/2/3.pdf
    // (mri_dataset/_unused/references/); shear speeds for bone are rough
    // placeholders (see TODO at top of file).

    auto cortical_bone_mat_fun = []() -> elastic_material_data<double> {
        double rho, vp, vs;
        rho = 1900.0;
        vp  = 2800.0;
        vs  = 1700.0;
        elastic_material_data<double> material(rho,vp,vs);
        return material;
    };

    auto cancellous_bone_mat_fun = []() -> elastic_material_data<double> {
        double rho, vp, vs;
        rho = 1200.0;
        vp  = 2100.0;
        vs  = 1300.0;
        elastic_material_data<double> material(rho,vp,vs);
        return material;
    };

    auto background_mat_fun = []() -> acoustic_material_data<double> {
        double rho, vp;
        rho = 1000.0;
        vp  = 1480.0;
        acoustic_material_data<double> material(rho,vp);
        return material;
    };

    auto csf_mat_fun = []() -> acoustic_material_data<double> {
        double rho, vp;
        rho = 1000.0;
        vp  = 1500.0;
        acoustic_material_data<double> material(rho,vp);
        return material;
    };

    auto gray_matter_mat_fun = []() -> acoustic_material_data<double> {
        double rho, vp;
        rho = 1040.0;
        vp  = 1508.0;
        acoustic_material_data<double> material(rho,vp);
        return material;
    };

    auto white_matter_mat_fun = []() -> acoustic_material_data<double> {
        double rho, vp;
        rho = 1040.0;
        vp  = 1491.0;
        acoustic_material_data<double> material(rho,vp);
        return material;
    };

    // ######################################################################
    // ###################################################################### Structure setting
    // ######################################################################

    std::map<size_t, elastic_material_data<RealType>>  brain_e_material;
    std::map<size_t, acoustic_material_data<RealType>> brain_a_material;
    std::map<size_t,std::pair<size_t,size_t>> interface_cell_pair_indexes;

    // Material ids 1,2 are elastic (see polygon_2d_mesh_reader::move_to_mesh_storage,
    // which sets m_elastic_material = (m_material == 1 || m_material == 2));
    // every other id is acoustic.
    for (auto & cell : msh ) {
        auto cell_ind = msh.lookup(cell);
        int material_id = mesh_builder.polygons[cell_ind].m_material;
        switch (material_id) {
            case 1: {
                elastic_material_data<RealType> material = cortical_bone_mat_fun();
                brain_e_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 2: {
                elastic_material_data<RealType> material = cancellous_bone_mat_fun();
                brain_e_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 3: {
                acoustic_material_data<RealType> material = background_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 4: {
                acoustic_material_data<RealType> material = csf_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 5: {
                acoustic_material_data<RealType> material = gray_matter_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 6: {
                acoustic_material_data<RealType> material = white_matter_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            default: {
                std::cout << "Warning:: unknown material id " << material_id
                          << " for cell " << cell_ind << ", treating as background." << std::endl;
                acoustic_material_data<RealType> material = background_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
        }
    }

    auto is_elastic_id = [](int material_id) { return material_id == 1 || material_id == 2; };

    // Face classification. Unlike BrainIHHOFirstOrder.hpp (which only needs
    // interface_cell_pair_indexes for the implicit LHS), the ERK scheme's
    // Sff_inverse (below) additionally needs every face bucketed as purely
    // elastic, purely acoustic, or on the elastic/acoustic interface - the
    // same three-way split HeterogeneousEHHOFirstOrder.hpp builds from a
    // geometric criterion (bar.y() > 0), done here from the material id.
    std::set<size_t> elastic_internal_faces, acoustic_internal_faces, interface_face_indexes;
    std::set<size_t> elastic_bc_face_indexes, acoustic_bc_face_indexes;

    auto conn = disk::connectivity_via_faces(msh);
    for (auto face_it = msh.faces_begin(); face_it != msh.faces_end(); face_it++) {
        const auto face = *face_it;
        auto fc_id = msh.lookup(face);
        auto connected_cells = conn.connected_cells(msh, face);
        std::vector<int> cell_inds;
        std::vector<int> materials;
        for (const auto& cell : connected_cells) {
            auto cell_ind = msh.lookup(cell);
            cell_inds.push_back(cell_ind);
            materials.push_back(mesh_builder.polygons[cell_ind].m_material);
        }

        if (materials.size() == 2) {
            bool e0 = is_elastic_id(materials[0]);
            bool e1 = is_elastic_id(materials[1]);
            if (e0 && e1) {
                elastic_internal_faces.insert(fc_id);
            }
            else if (!e0 && !e1) {
                acoustic_internal_faces.insert(fc_id);
            }
            else {
                interface_face_indexes.insert(fc_id);
                if (e1) {
                    interface_cell_pair_indexes[fc_id].first  = cell_inds[1];
                    interface_cell_pair_indexes[fc_id].second = cell_inds[0];
                }
                else {
                    interface_cell_pair_indexes[fc_id].first  = cell_inds[0];
                    interface_cell_pair_indexes[fc_id].second = cell_inds[1];
                }
            }
        }
        else {
            // boundary face: single connected cell
            if (is_elastic_id(materials[0]))
                elastic_internal_faces.insert(fc_id);
            else
                acoustic_internal_faces.insert(fc_id);
        }
    }

    auto null_s_fun = [](const disk::mesh<double, 2, disk::generic_mesh_storage<double, 2>>::point_type& pt) -> double {
      return 0.0;
    };

    auto null_fun = [](const disk::mesh<double, 2, disk::generic_mesh_storage<double, 2>>::point_type& pt) -> disk::static_vector<double, 2> {
      disk::static_vector<double, 2> f{0,0};
      return f;
    };

    auto null_flux_fun = [](const typename disk::mesh<double, 2, disk::generic_mesh_storage<double, 2>>::point_type& pt) -> disk::static_matrix<double,2,2> {
      double x,y;
      x = pt.x();
      y = pt.y();
      disk::static_matrix<double, 2, 2> sigma = disk::static_matrix<double,2,2>::Zero(2,2);
      return sigma;
    };

    // Boundary faces - re-tag boundary_info by the material of the (single)
    // adjacent cell, following HeterogeneousEHHOFirstOrder.hpp. This also
    // fixes the mismatch noted in BrainIHHOFirstOrder.hpp, where every
    // boundary edge came out of the reader tagged 0 regardless of material,
    // so a Dirichlet BC declared on tag 1 (acoustic) never matched anything.
    size_t bc_elastic_id  = 0;
    size_t bc_acoustic_id = 1;
    for (auto face_it = msh.boundary_faces_begin(); face_it != msh.boundary_faces_end(); face_it++) {
        auto face = *face_it;
        auto fc_id = msh.lookup(face);
        bool is_elastic_face = elastic_internal_faces.find(fc_id) != elastic_internal_faces.end();
        if (is_elastic_face) {
            disk::boundary_descriptor bi{bc_elastic_id, true};
            msh.backend_storage()->boundary_info.at(fc_id) = bi;
            elastic_bc_face_indexes.insert(fc_id);
        }
        else {
            disk::boundary_descriptor bi{bc_acoustic_id, true};
            msh.backend_storage()->boundary_info.at(fc_id) = bi;
            acoustic_bc_face_indexes.insert(fc_id);
        }
    }

    e_boundary_type e_bnd(msh);
    a_boundary_type a_bnd(msh);
    e_bnd.addDirichletBC(disk::DirichletType::DIRICHLET, bc_elastic_id, null_fun);
    a_bnd.addDirichletBC(disk::DirichletType::DIRICHLET, bc_acoustic_id, null_s_fun);

    // ##################################################
    // ################################################## Solving a primal HHO mixed problem
    // ##################################################

    tc.tic();
    auto assembler = elastoacoustic_four_fields_assembler<mesh_type>(msh, hho_di, e_bnd, a_bnd, brain_e_material, brain_a_material);
    assembler.set_interface_cell_indexes(interface_cell_pair_indexes);
    assembler.set_hdg_stabilization();
    if(sim_data.m_scaled_stabilization_Q)
        assembler.set_scaled_stabilization();

    tc.toc();
    std::cout << bold << red << "   ASSEMBLY 1 : " << std::endl;
    std::cout << bold << cyan << "      Assembler generation : ";
    std::cout << tc << " seconds" << reset << std::endl;

    tc.tic();
    assembler.assemble_mass(msh);
    tc.toc();
    std::cout << bold << cyan << "      Mass Assembly : ";
    std::cout << tc << " seconds" << reset << std::endl;

    tc.tic();
    assembler.assemble_coupling_terms(msh);
    tc.toc();
    std::cout << bold << cyan << "      Coupling assembly : ";
    std::cout << tc << " seconds" << reset << std::endl << std::endl;

    // ######################################################################
    // ###################################################################### Projecting initial data
    // ######################################################################
    //
    // Same Ricker wavelet as BrainIHHOFirstOrder.hpp, sourced in the
    // ACOUSTIC field only (brain center is soft tissue) - see that file for
    // the full rationale. xc, yc: centroid of gray+white matter in the
    // regularized array used to build meshes/brain.txt - recompute if the
    // mesh is regenerated at a different resolution/downsampling.

    auto ricker_pulse_brain = [](const disk::mesh<double, 2, disk::generic_mesh_storage<double, 2>>::point_type& pt) -> double {
        double x,y,xc,yc,a,r2,u;
        x  = pt.x();
        y  = pt.y();
        xc = 95.20;
        yc = 94.15;
        a  = 3.0;
        r2 = (x-xc)*(x-xc) + (y-yc)*(y-yc);
        u  = r2/(a*a);
        return (1.0 - 2.0*u) * std::exp(-u);
    };

    Matrix<RealType, Dynamic, 1> x_dof;
    assembler.project_over_cells(msh, x_dof, null_fun, null_flux_fun, ricker_pulse_brain, null_fun);
    assembler.project_over_faces(msh, x_dof, null_fun, ricker_pulse_brain);

    if (sim_data.m_render_silo_files_Q) {
        size_t it = 0;
        std::string silo_file_name = "EBrain_silo_initial_";
        postprocessor<mesh_type>::write_silo_four_fields_elastoacoustic(silo_file_name, it, msh, hho_di, x_dof, brain_e_material, brain_a_material, false);
    }

    // ##################################################
    // ################################################## Solving a first order equation HDG/HHO propagation problem
    // ##################################################

    Matrix<RealType, Dynamic, Dynamic> a;
    Matrix<RealType, Dynamic, 1> b;
    Matrix<RealType, Dynamic, 1> c;

    // ERK(s) scheme
    int s = 4;
    erk_butcher_tableau::erk_tables(s, a, b, c);

    std::cout << bold << red << "   ASSEMBLY 2 : " << std::endl;
    std::cout << bold << cyan << "      First stiffness assembly completed: ";
    tc.tic();
    assembler.assemble(msh, null_fun, null_s_fun, true);
    tc.toc();
    std::cout << bold << cyan << tc << " seconds" << reset << std::endl;
    assembler.LHS += assembler.COUPLING;

    size_t elastic_cell_dofs  = assembler.get_e_n_cells_dof();
    size_t acoustic_cell_dofs = assembler.get_a_n_cells_dof();
    size_t e_face_dofs = assembler.get_e_face_dof();
    size_t a_face_dofs = assembler.get_a_face_dof();

    tc.tic();
    erk_coupling_hho_scheme<RealType> erk_an(assembler.LHS, assembler.RHS, assembler.MASS, assembler.COUPLING, elastic_cell_dofs, acoustic_cell_dofs, e_face_dofs, a_face_dofs);
    erk_an.Mcc_inverse(assembler.get_elastic_cells(), assembler.get_acoustic_cells(), assembler.get_e_cell_basis_data(), assembler.get_a_cell_basis_data());
    erk_an.Sff_inverse(assembler.get_elastic_faces(), assembler.get_acoustic_faces(), assembler.get_e_face_basis_data(), assembler.get_a_face_basis_data(), assembler.get_e_compress(), assembler.get_a_compress(), elastic_internal_faces, acoustic_internal_faces, interface_face_indexes);
    tc.toc();
    std::cout << bold << cyan << "      ERK analysis created: " << tc << " seconds" << reset << std::endl;

    tc.tic();
    erk_an.refresh_faces_unknowns(x_dof);
    tc.toc();
    std::cout << bold << cyan << "      Inverse of Sff + Coupling in: " << tc << " seconds" << reset << std::endl;

    // ##################################################
    // ################################################## Preprocessor
    // ##################################################

    std::ostringstream filename;
    filename << "EBrain_l_" << sim_data.m_n_divs << "_n_" << sim_data.m_nt_divs << "_k_" << sim_data.m_k_degree << "_s_" << s << ".txt";
    std::string filename_str = filename.str();
    std::ofstream simulation_log(filename_str);
    sim_data.write_simulation_data(simulation_log);
    simulation_log << "Number of ERK steps =  " << s << std::endl;
    simulation_log << "Number of time steps =  " << nt << std::endl;
    simulation_log << "Step size =  " << dt << std::endl;
    simulation_log << "Number of equations : " << assembler.RHS.rows() << std::endl;
    simulation_log << "Space step = " << h << std::endl;
    simulation_log.flush();

    std::ostringstream filename_e;
    filename_e << "energy_l_" << sim_data.m_n_divs << "_n_" << sim_data.m_nt_divs << "_k_" << sim_data.m_k_degree << "_s_" << s << "_discret_" << sim_data.m_hdg_stabilization_Q << ".txt";
    std::string filename_e_str = filename_e.str();
    std::ofstream energy_file(filename_e_str);
    if (sim_data.m_report_energy_Q)
        postprocessor<mesh_type>::compute_elasto_acoustic_energy_four_field(msh, hho_di, assembler, t, x_dof, energy_file);

    std::cout << std::endl;

    // ##################################################
    // ################################################## Time marching
    // ##################################################

    Matrix<RealType, Dynamic, 1> x_dof_n;
    for(size_t it = 1; it <= nt; it++) {

        tcit.tic();
        std::cout << bold << red << "   Time step number " << it << ": t = " << t << reset << std::endl;

        // ERK step
        tc.tic();
        {
            size_t n_dof = x_dof.rows();
            Matrix<RealType, Dynamic, Dynamic> k = Matrix<RealType, Dynamic, Dynamic>::Zero(n_dof, s);
            Matrix<RealType, Dynamic, 1> yn, ki;
            x_dof_n = x_dof;
            for (int i = 0; i < s; i++) {
                yn = x_dof;
                for (int j = 0; j < s - 1; j++)
                    yn += a(i,j) * dt * k.block(0, j, n_dof, 1);
                erk_an.erk_weight(yn, ki);
                // Accumulated solution
                x_dof_n += dt*b(i,0)*ki;
                k.block(0, i, n_dof, 1) = ki;
            }
        }
        tc.toc();
        std::cout << bold << cyan << "      ERK step completed: " << tc << " seconds" << reset << std::endl;

        x_dof = x_dof_n;

        // ##################################################
        // ################################################## Last postprocess
        // ##################################################

        int silo_mod = static_cast<int>(std::round(nt / 15.0)); // Number of silo files
        if (silo_mod < 1)
            silo_mod = 1;
        if ((!sim_data.m_render_silo_files_Q && (it == 1 || it == std::round(nt/2) || it == nt)) || (sim_data.m_render_silo_files_Q && (it%silo_mod == 0))) {
            std::ostringstream filename;
            filename << "EBrain_silo_l_" << sim_data.m_n_divs << "_n_" << sim_data.m_nt_divs << "_k_" << sim_data.m_k_degree << "_s_" << s << "_";
            std::string silo_file_name = filename.str();
            postprocessor<mesh_type>::write_silo_four_fields_elastoacoustic(silo_file_name, it, msh, hho_di, x_dof, brain_e_material, brain_a_material, false);
            std::cout << bold << cyan << "      Silo file generated" << reset << std::endl;
        }

        if (sim_data.m_report_energy_Q) {
            postprocessor<mesh_type>::compute_elasto_acoustic_energy_four_field(msh, hho_di, assembler, t, x_dof, energy_file);
        }

        t += dt;

        tcit.toc();
        std::cout << bold << cyan << "      Iteration completed in " << tcit << " seconds" << reset << std::endl << std::endl;

        if (it == nt) {
            std::ostringstream filename;
            filename << "Esilo_l_" << sim_data.m_n_divs << "_n_" << sim_data.m_nt_divs << "_k_" << sim_data.m_k_degree << "_s_" << s << "_";
            std::string silo_file_name = filename.str();
            postprocessor<mesh_type>::write_silo_four_fields_elastoacoustic(silo_file_name, it, msh, hho_di, x_dof, brain_e_material, brain_a_material, false);
        }

    }

    cpu.toc();
    simulation_log << "TOTAL CPU TIME: " << cpu << std::endl;
    std::cout << bold << red << "   TOTAL CPU TIME: " << cpu << std::endl << std::endl;

}
