

//  Created by Romain Mottier
//  Adapted from BassinIHHOFirstOrder.hpp for the segmented-brain application.
//
//  TODO before this is physically meaningful:
//   - time range, pulse location/frequency and the pixel-to-distance scale
//     are placeholders copied from Basin and must be set once the physical
//     scale of the segmentation mesh (mm/pixel, excitation source) is fixed
//   - bone shear-wave speeds (vs) below are rough literature placeholders,
//     not sourced the way the P-wave speeds were (see wave_speeds_*.pdf)


void BrainIHHOFirstOrder(int argc, char **argv);

void BrainIHHOFirstOrder(int argc, char **argv){

    // ######################################################################
    // ###################################################################### Simulation paramaters
    // ######################################################################

    std::cout << std::endl << bold << red << "   IMPLICIT BRAIN (MRI SEGMENTATION)" << std::endl;
    using RealType = double;
    simulation_data sim_data = preprocessor::process_args(argc, argv);
    sim_data.print_simulation_data();
    timecounter tc, tcit, cpu;
    cpu.tic();

    // ######################################################################
    // ###################################################################### Mesh generation
    // ######################################################################

    tc.tic();
    typedef disk::mesh<RealType, 2, disk::generic_mesh_storage<RealType, 2>>  mesh_type;
    typedef disk::BoundaryConditions<mesh_type, false> e_boundary_type;
    typedef disk::BoundaryConditions<mesh_type, true> a_boundary_type;
    mesh_type msh;

    auto validate_l = [](size_t l) -> size_t {
        if ((0 <= l) && (l < 1) ) {
            return l;
        }
        else {
            std::cout << std::endl << std::endl;
            std::cout << "Warning:: Only few polygonal meshes available.";
            std::cout << std::endl << std::endl;
            return 0;
        }
    };

    size_t l = validate_l(sim_data.m_n_divs);
    polygon_2d_mesh_reader<RealType> mesh_builder;
    std::vector<std::string> mesh_files;

    mesh_files.push_back("../meshes/brain.txt");    // l = 0, generated by mri_dataset/generate_mesh.py

    // Reading the polygonal mesh (same reader/format as the Basin case:
    // build_bassin() is format-generic, it just reads whatever integer
    // material id is stored per polygon)
    mesh_builder.set_poly_mesh_file(mesh_files[l]);
    mesh_builder.build_bassin();
    mesh_builder.move_to_mesh_storage(msh);
    mesh_builder.remove_duplicate_points();

    RealType h = 10;
    for (auto & cell : msh ) {
        auto cell_ind = msh.lookup(cell);
        mesh_type::point_type bar = barycenter(msh, cell);
        RealType h_l = diameter(msh, cell);
        if (h_l < h)
            h = h_l;
    }

    tc.toc();
    std::cout << bold << red << "   MESH GENERATION : ";
    std::cout << tc << " seconds" << reset << std::endl << std::endl;

    // ######################################################################
    // ###################################################################### Time controls
    // ######################################################################

    size_t nt = 10;
    for (unsigned int i = 0; i < sim_data.m_nt_divs; i++) {
        nt *= 2;
        // nt = sim_data.m_nt_divs;
    }

    RealType ti = 0.0;
    RealType tf = 0.1;
    RealType dt = (tf-ti)/nt;
    RealType t  = ti;

    // ######################################################################
    // ###################################################################### HHO setting
    // ######################################################################

    // Creating HHO approximation spaces and corresponding linear operator
    size_t cell_k_degree = sim_data.m_k_degree;
    if(sim_data.m_hdg_stabilization_Q)
        cell_k_degree++;

    disk::hho_degree_info hho_di(cell_k_degree,sim_data.m_k_degree);

    // ##################################################
    // ################################################## Material data
    // ##################################################
    //
    // Material ids (assigned in mri_dataset/generate_mesh.py, MATERIAL_IDS):
    //   1 : cortical bone (outer + inner table)   -> elastic
    //   2 : cancellous bone (diploe)               -> elastic
    //   3 : background                             -> acoustic
    //   4 : cerebrospinal fluid (CSF)               -> acoustic
    //   5 : gray matter                             -> acoustic
    //   6 : white matter                            -> acoustic
    //
    // P-wave speeds and densities sourced from wave_speeds_1/2/3.pdf
    // (mri_dataset/_unused/references/); shear speeds for bone are rough
    // placeholders (see TODO at top of file).

    auto cortical_bone_mat_fun = []() -> elastic_material_data<double> {
        double rho, vp, vs;
        rho = 1900.0;
        vp  = 2800.0;
        vs  = 1700.0;
        elastic_material_data<double> material(rho,vp,vs);
        return material;
    };

    auto cancellous_bone_mat_fun = []() -> elastic_material_data<double> {
        double rho, vp, vs;
        rho = 1200.0;
        vp  = 2100.0;
        vs  = 1300.0;
        elastic_material_data<double> material(rho,vp,vs);
        return material;
    };

    auto background_mat_fun = []() -> acoustic_material_data<double> {
        double rho, vp;
        rho = 1000.0;
        vp  = 1480.0;
        acoustic_material_data<double> material(rho,vp);
        return material;
    };

    auto csf_mat_fun = []() -> acoustic_material_data<double> {
        double rho, vp;
        rho = 1000.0;
        vp  = 1500.0;
        acoustic_material_data<double> material(rho,vp);
        return material;
    };

    auto gray_matter_mat_fun = []() -> acoustic_material_data<double> {
        double rho, vp;
        rho = 1040.0;
        vp  = 1508.0;
        acoustic_material_data<double> material(rho,vp);
        return material;
    };

    auto white_matter_mat_fun = []() -> acoustic_material_data<double> {
        double rho, vp;
        rho = 1040.0;
        vp  = 1491.0;
        acoustic_material_data<double> material(rho,vp);
        return material;
    };

    // ######################################################################
    // ###################################################################### Structure setting
    // ######################################################################

    std::map<size_t, elastic_material_data<RealType>>  brain_e_material;
    std::map<size_t, acoustic_material_data<RealType>> brain_a_material;
    std::map<size_t,std::pair<size_t,size_t>> interface_cell_pair_indexes;

    // Material ids 1,2 are elastic (see polygon_2d_mesh_reader::move_to_mesh_storage,
    // which sets m_elastic_material = (m_material == 1 || m_material == 2));
    // every other id is acoustic. Unlike the Basin case (a single acoustic
    // id, 3, for air), the brain mesh carries four distinct acoustic ids.
    for (auto & cell : msh ) {
        auto cell_ind = msh.lookup(cell);
        int material_id = mesh_builder.polygons[cell_ind].m_material;
        switch (material_id) {
            case 1: {
                elastic_material_data<RealType> material = cortical_bone_mat_fun();
                brain_e_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 2: {
                elastic_material_data<RealType> material = cancellous_bone_mat_fun();
                brain_e_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 3: {
                acoustic_material_data<RealType> material = background_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 4: {
                acoustic_material_data<RealType> material = csf_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 5: {
                acoustic_material_data<RealType> material = gray_matter_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            case 6: {
                acoustic_material_data<RealType> material = white_matter_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
            default: {
                std::cout << "Warning:: unknown material id " << material_id
                          << " for cell " << cell_ind << ", treating as background." << std::endl;
                acoustic_material_data<RealType> material = background_mat_fun();
                brain_a_material.insert(std::make_pair(cell_ind,material));
                break;
            }
        }
    }

    // Detect interfaces. Generalized from the Basin version (which only
    // checked materials[i] == 3): any material id other than 1 or 2 is
    // acoustic here, so the elastic/acoustic test below must match that.
    auto is_elastic_id = [](int material_id) { return material_id == 1 || material_id == 2; };

    // Also classify every face as purely elastic or purely acoustic (needed
    // below to re-tag boundary faces by material - see BrainEHHOFirstOrder.hpp,
    // which fixed this same issue: the reader always tags boundary edges 0
    // regardless of material, so a Dirichlet BC declared on tag 1 (acoustic)
    // never matched anything and the whole outer background boundary ran
    // without any imposed condition).
    std::set<size_t> elastic_internal_faces, acoustic_internal_faces;

    auto conn = disk::connectivity_via_faces(msh);
    for (auto face_it = msh.faces_begin(); face_it != msh.faces_end(); face_it++) {
        const auto face = *face_it;
        auto fc_id = msh.lookup(face);
        auto connected_cells = conn.connected_cells(msh, face);
        std::vector<int> cell_inds;
        std::vector<int> materials;
        for (const auto& cell : connected_cells) {
            auto cell_ind = msh.lookup(cell);
            cell_inds.push_back(cell_ind);
            materials.push_back(mesh_builder.polygons[cell_ind].m_material);
        }

        if (materials.size() == 2) {
            bool e0 = is_elastic_id(materials[0]);
            bool e1 = is_elastic_id(materials[1]);

            if (!e0 && e1) {
                interface_cell_pair_indexes[fc_id].first = cell_inds[1];
                interface_cell_pair_indexes[fc_id].second = cell_inds[0];
                continue;
            }
            if (!e1 && e0) {
                interface_cell_pair_indexes[fc_id].first = cell_inds[0];
                interface_cell_pair_indexes[fc_id].second = cell_inds[1];
                continue;
            }
            if (e0 && e1)
                elastic_internal_faces.insert(fc_id);
            else
                acoustic_internal_faces.insert(fc_id);
        }
        else {
            // boundary face: single connected cell
            if (is_elastic_id(materials[0]))
                elastic_internal_faces.insert(fc_id);
            else
                acoustic_internal_faces.insert(fc_id);
        }
    }

    auto null_s_fun = [](const disk::mesh<double, 2, disk::generic_mesh_storage<double, 2>>::point_type& pt) -> double {
      return 0.0;
    };

    auto null_fun = [](const disk::mesh<double, 2, disk::generic_mesh_storage<double, 2>>::point_type& pt) -> disk::static_vector<double, 2> {
      disk::static_vector<double, 2> f{0,0};
      return f;
    };

    auto null_flux_fun = [](const typename disk::mesh<double, 2, disk::generic_mesh_storage<double, 2>>::point_type& pt) -> disk::static_matrix<double,2,2> {
      double x,y;
      x = pt.x();
      y = pt.y();
      disk::static_matrix<double, 2, 2> sigma = disk::static_matrix<double,2,2>::Zero(2,2);
      return sigma;
    };

    // Boundary faces - re-tag boundary_info by the material of the (single)
    // adjacent cell (see BrainEHHOFirstOrder.hpp for the rationale): without
    // this, every boundary edge keeps the reader's default tag 0, so the
    // acoustic Dirichlet BC below (declared on tag 1) never matches anything.
    size_t bc_elastic_id  = 0;
    size_t bc_acoustic_id = 1;
    std::set<size_t> elastic_bc_face_indexes, acoustic_bc_face_indexes;
    for (auto face_it = msh.boundary_faces_begin(); face_it != msh.boundary_faces_end(); face_it++) {
        auto face = *face_it;
        auto fc_id = msh.lookup(face);
        bool is_elastic_face = elastic_internal_faces.find(fc_id) != elastic_internal_faces.end();
        if (is_elastic_face) {
            disk::boundary_descriptor bi{bc_elastic_id, true};
            msh.backend_storage()->boundary_info.at(fc_id) = bi;
            elastic_bc_face_indexes.insert(fc_id);
        }
        else {
            disk::boundary_descriptor bi{bc_acoustic_id, true};
            msh.backend_storage()->boundary_info.at(fc_id) = bi;
            acoustic_bc_face_indexes.insert(fc_id);
        }
    }

    e_boundary_type e_bnd(msh);
    a_boundary_type a_bnd(msh);

    e_bnd.addDirichletBC(disk::DirichletType::DIRICHLET, bc_elastic_id, null_fun);
    a_bnd.addDirichletBC(disk::DirichletType::DIRICHLET, bc_acoustic_id, null_s_fun);

    // ##################################################
    // ################################################## Solving a primal HHO mixed problem
    // ##################################################

    tc.tic();
    auto assembler = elastoacoustic_four_fields_assembler<mesh_type>(msh, hho_di, e_bnd, a_bnd, brain_e_material, brain_a_material);
    assembler.set_interface_cell_indexes(interface_cell_pair_indexes);
    assembler.set_hdg_stabilization();
    if(sim_data.m_scaled_stabilization_Q)
        assembler.set_scaled_stabilization();

    tc.toc();
    std::cout << bold << red << "   ASSEMBLY 1 : " << std::endl;
    std::cout << bold << cyan << "      Assembler generation : ";
    std::cout << tc << " seconds" << reset << std::endl;

    tc.tic();
    assembler.assemble_mass(msh);
    tc.toc();
    std::cout << bold << cyan << "      Mass Assembly : ";
    std::cout << tc << " seconds" << reset << std::endl;

    tc.tic();
    assembler.assemble_coupling_terms(msh);
    tc.toc();
    std::cout << bold << cyan << "      Coupling assembly : ";
    std::cout << tc << " seconds" << reset << std::endl << std::endl;

    // ######################################################################
    // ###################################################################### Projecting initial data
    // ######################################################################
    //
    // Ricker wavelet (Mexican-hat) initial condition, sourced in the
    // ACOUSTIC field only (v_s_fun, the 3rd argument of project_over_cells)
    // since the brain center is soft tissue (acoustic in our material
    // scheme, see MATERIAL_IDS in mri_dataset/generate_mesh.py) - only bone
    // is elastic. The elastic velocity (v_fun) is left at zero: the point of
    // this test is to see whether the wave excites the bone at all, which
    // only happens through the elastic/acoustic coupling terms, not because
    // we seeded the solid directly.
    //
    // xc, yc: centroid of gray+white matter (labels 5,6) in the exact
    // regularized array used to build meshes/brain.txt (mri_dataset/
    // brain_wide.npy, FULL RESOLUTION, no downsample) - recompute (see
    // mri_dataset, np.isin(a,[5,6]).nonzero() centroid) if the mesh is
    // regenerated from a different slice/downsampling; it was previously
    // (47.57, 47.25) for a downsample-2 mesh - halving the domain silently
    // moved the "center" pulse next to the skull instead of mid-brain.
    // a: pulse radius, deliberately small versus the ~130-unit brain extent.

    auto ricker_pulse_brain = [](const disk::mesh<double, 2, disk::generic_mesh_storage<double, 2>>::point_type& pt) -> double {
        double x,y,xc,yc,a,r2,u;
        x  = pt.x();
        y  = pt.y();
        xc = 95.20;
        yc = 94.15;
        a  = 3.0;
        r2 = (x-xc)*(x-xc) + (y-yc)*(y-yc);
        u  = r2/(a*a);
        return (1.0 - 2.0*u) * std::exp(-u);
    };

    Matrix<RealType, Dynamic, 1> x_dof;
    assembler.project_over_cells(msh, x_dof, null_fun, null_flux_fun, ricker_pulse_brain, null_fun);
    assembler.project_over_faces(msh, x_dof, null_fun, ricker_pulse_brain);

    // ##################################################
    // ################################################## Solving a first order equation HDG/HHO propagation problem
    // ##################################################

    Matrix<RealType, Dynamic, Dynamic> a;
    Matrix<RealType, Dynamic, 1> b;
    Matrix<RealType, Dynamic, 1> c;

    // DIRK(s) schemes
    int s = 3;
    bool is_sdirk_Q = true;
    if (is_sdirk_Q) {
        dirk_butcher_tableau::sdirk_tables(s, a, b, c);
    }
    else {
        dirk_butcher_tableau::dirk_tables(s, a, b, c);
    }

    std::cout << bold << red << "   ASSEMBLY 2 : " << std::endl;
    std::cout << bold << cyan << "      First stiffness assembly completed: ";
    tc.tic();
    assembler.assemble(msh, null_fun, null_s_fun, false);
    tc.toc();
    std::cout << bold << cyan << tc << " seconds" << reset << std::endl;
    assembler.LHS += assembler.COUPLING;
    dirk_hho_scheme<RealType> dirk_an(assembler.LHS,assembler.RHS,assembler.MASS);

    if (sim_data.m_sc_Q) {
        std::vector<std::pair<size_t,size_t>> vec_cell_basis_data(2);
        vec_cell_basis_data[0] = std::make_pair(assembler.get_e_material_data().size(), assembler.get_e_cell_basis_data());
        vec_cell_basis_data[1] = std::make_pair(assembler.get_a_material_data().size(), assembler.get_a_cell_basis_data());
        dirk_an.set_static_condensation_data(vec_cell_basis_data, assembler.get_n_face_dof());
    }

    if (is_sdirk_Q) {
        double scale = a(0,0) * dt;
        dirk_an.SetScale(scale);
        std::cout << bold << cyan << "      Matrix decomposed: ";
        tc.tic();
        dirk_an.ComposeMatrix();
        bool iteratif_solver = false; // if false load library: source /opt/intel/oneapi/setvars.sh intel64
        if (iteratif_solver)
            dirk_an.setIterativeSolver();
        dirk_an.DecomposeMatrix();
        tc.toc();
        std::cout << tc << " seconds" << reset << std::endl;
    }

    // ##################################################
    // ################################################## Preprocessor
    // ##################################################

    std::ostringstream filename;
    filename << "IBrain_l_" << sim_data.m_n_divs << "_n_" << sim_data.m_nt_divs << "_k_" << sim_data.m_k_degree << "_s_" << s << ".txt";
    std::string filename_str = filename.str();
    std::ofstream simulation_log(filename_str);
    sim_data.write_simulation_data(simulation_log);
    simulation_log << "Number of SDIRK steps =  " << s << std::endl;
    simulation_log << "Number of time steps =  " << nt << std::endl;
    simulation_log << "Step size =  " << dt << std::endl;
    simulation_log << "Number of equations : " << assembler.RHS.rows() << std::endl;
    simulation_log << "Space step = " << h << std::endl;
    simulation_log.flush();

    if (sim_data.m_render_silo_files_Q) {
        size_t it = 0;
        std::ostringstream filename;
        filename << "IBrain_silo_l_" << sim_data.m_n_divs << "_n_" << sim_data.m_nt_divs << "_k_" << sim_data.m_k_degree << "_s_" << s << "_";
        std::string silo_file_name = filename.str();
        postprocessor<mesh_type>::write_silo_four_fields_elastoacoustic(silo_file_name, it, msh, hho_di, x_dof, brain_e_material, brain_a_material, false);
    }

    std::ostringstream filename_e;
    filename_e << "energy_l_" << sim_data.m_n_divs << "_n_" << sim_data.m_nt_divs << "_k_" << sim_data.m_k_degree << "_s_" << s << "_discret_" << sim_data.m_hdg_stabilization_Q << ".txt";
    std::string filename_e_str = filename_e.str();
    std::ofstream energy_file(filename_e_str);
    if (sim_data.m_report_energy_Q)
        postprocessor<mesh_type>::compute_elasto_acoustic_energy_four_field(msh, hho_di, assembler, t, x_dof, energy_file);

    std::cout << std::endl;

    // ##################################################
    // ################################################## Time marching
    // ##################################################

    Matrix<RealType, Dynamic, 1> x_dof_n;
    for(size_t it = 1; it <= nt; it++) {

        tcit.tic();
        std::cout << bold << red << "   Time step number " << it << ": t = " << t << reset << std::endl;
        RealType tn = dt*(it-1)+ti;

        // DIRK step
        tc.tic();
        {
            size_t n_dof = x_dof.rows();
            Matrix<double, Dynamic, Dynamic> k = Matrix<double, Dynamic, Dynamic>::Zero(n_dof, s);
            Matrix<double, Dynamic, 1> Fg, Fg_c, xd;
            xd = Matrix<double, Dynamic, 1>::Zero(n_dof, 1);

            RealType t;
            Matrix<double, Dynamic, 1> yn, ki;
            x_dof_n = x_dof;
            for (int i = 0; i < s; i++) {
                yn = x_dof;
                for (int j = 0; j < s - 1; j++)
                    yn += a(i,j) * dt * k.block(0, j, n_dof, 1);
                t = tn + c(i,0) * dt;
                assembler.RHS.setZero(); // No souce term
                dirk_an.SetFg(assembler.RHS);
                dirk_an.irk_weight(yn, ki, dt, a(i,i), is_sdirk_Q);
                // Accumulated solution
                x_dof_n += dt*b(i,0)*ki;
                k.block(0, i, n_dof, 1) = ki;
            }
        }
        tc.toc();
        std::cout << bold << cyan << "      DIRK step completed: " << tc << " seconds"  << reset << std::endl;

        x_dof = x_dof_n;

        // ##################################################
        // ################################################## Last postprocess
        // ##################################################

        int silo_mod = static_cast<int>(std::round(nt / 15.0)); // Number of silo files
        if ((!sim_data.m_render_silo_files_Q && (it == 1 || it == std::round(nt/2) || it == nt)) || (sim_data.m_render_silo_files_Q && (it%silo_mod == 0))) {
            std::ostringstream filename;
            filename << "IBrain_silo_l_" << sim_data.m_n_divs << "_n_" << sim_data.m_nt_divs << "_k_" << sim_data.m_k_degree << "_s_" << s << "_";
            std::string silo_file_name = filename.str();
            postprocessor<mesh_type>::write_silo_four_fields_elastoacoustic(silo_file_name, it, msh, hho_di, x_dof, brain_e_material, brain_a_material, false);
            std::cout << bold << cyan << "      Silo file generated" << reset << std::endl;
        }

        if (sim_data.m_report_energy_Q) {
            postprocessor<mesh_type>::compute_elasto_acoustic_energy_four_field(msh, hho_di, assembler, t, x_dof, energy_file);
        }

        t += dt;

        tcit.toc();
        std::cout << bold << cyan << "      Iteration completed in " << tcit << " seconds" << reset << std::endl << std::endl;

        if (it == nt) {
            std::ostringstream filename;
            filename << "silo_l_" << sim_data.m_n_divs << "_n_" << sim_data.m_nt_divs << "_k_" << sim_data.m_k_degree << "_s_" << s << "_";
            std::string silo_file_name = filename.str();
            postprocessor<mesh_type>::write_silo_four_fields_elastoacoustic(silo_file_name, it, msh, hho_di, x_dof, brain_e_material, brain_a_material, false);
        }

    }

    cpu.toc();
    simulation_log << "TOTAL CPU TIME: " << cpu << std::endl;
    std::cout << bold << red << "   TOTAL CPU TIME: " << cpu << std::endl << std::endl;

}
