import sympy as sp

print("")
print("")
print("")
# Définir les variables
t, x, y = sp.symbols('t x y')
rac2 = sp.symbols('rac2')

# ##############################################3 CUBIC EN ESPACE

print("ACOUSTIC DOMAIN CUBIC IN SPACE")
u = (1-x*x)*y*(1-y)*sp.sin(sp.pi*t)
print("u = ") 
sp.pprint(u)
v = sp.diff(u, t)
print("v = ") 
sp.pprint(v)
a = sp.diff(v, t)
print("a = ") 
sp.pprint(a)
grad_vx = sp.diff(v, x)
grad_vy = sp.diff(v, y)
# print("grad_vx = ") 
# sp.pprint(grad_vx)
print("")
# print("grad_vy = ")
# sp.pprint(grad_vy)

print("")
print("")
sigma_x = sp.diff(u, x)
print("sigma_x = ") 
sp.pprint(sigma_x)
sigma_y = sp.diff(u, y)
print("sigma_y = ") 
sp.pprint(sigma_y)
print("")
sigma_x_dt = sp.diff(sigma_x, t)
# print("sigma_x_dt = ") 
# sp.pprint(sigma_x_dt)
print("")
sigma_y_dt = sp.diff(sigma_y, t)
# print("sigma_y_dt = ") 
# sp.pprint(sigma_y_dt)


print("")
print("f = ")
f = a - sp.diff(sigma_x, x) - sp.diff(sigma_y, y)
sp.pprint(f)
print("")

# ##############################################3 CUBIC EN TEMPS 
# print("ACOUSTIC DOMAIN CUBIC IN TIME")
# u = sp.sin(sp.pi*x) * sp.sin(sp.pi*y) * t*t*t*t
# print("u = ") 
# sp.pprint(u)
# v = sp.diff(u, t)
# print("v = ") 
# sp.pprint(v)
# a = sp.diff(v, t)
# print("a = ") 
# sp.pprint(a)
# grad_vx = sp.diff(v, x)
# grad_vy = sp.diff(v, y)
# # print("grad_vx = ") 
# # sp.pprint(grad_vx)
# print("")
# # print("grad_vy = ")
# # sp.pprint(grad_vy)



# print("")
# print("")
# sigma_x = sp.diff(u, x)
# print("sigma_x = ") 
# sp.pprint(sigma_x)
# sigma_y = sp.diff(u, y)
# print("sigma_y = ") 
# sp.pprint(sigma_y)
# print("")
# sigma_x_dt = sp.diff(sigma_x, t)
# # print("sigma_x_dt = ") 
# # sp.pprint(sigma_x_dt)
# print("")
# sigma_y_dt = sp.diff(sigma_y, t)
# # print("sigma_y_dt = ") 
# # sp.pprint(sigma_y_dt)


# print("")
# print("f = ")
# f = a - sp.diff(sigma_x, x) - sp.diff(sigma_y, y)
# sp.pprint(f)
# print("")