
//  Created by Romain Mottier
//
// ERK4-LTS + HHO on a graded L-shaped mesh (reentrant-corner benchmark),
// following Grote, Michel, Sauter, "Stabilized leapfrog based local
// time-stepping method for the wave equation" (arXiv:2005.13350), Sec. 4.3.
//
// Domain Omega = (0,1)^2 \ [0.5,1)x(0.5,1], reentrant corner at (0.5,0.5).
// Mesh: fan/polar graded triangulation centered at the reentrant corner
// (Omega is star-shaped w.r.t. it), generated by
// mesh_generation/lshape_graded/generate_lshape_graded_mesh.py and read back
// via polygon_2d_mesh_reader (poly_2d text format).
//
// Pure acoustic problem (no elastic side, no interface): first-order mixed
// HHO state (V_T flux/velocity, P_T/P_F pressure), time-integrated with the
// existing LTS-RK4(p) scheme (erk_coupling_hho_scheme, "Algorithm 3"). The
// fine/coarse split needed by LTS is obtained "for free" from
// assembler.assemble_P(msh, h_c, nb_layer): it thresholds cells by diameter
// vs h_c, and since the graded mesh's smallest cells sit at the corner by
// construction, this reproduces the paper's "N layers from the corner"
// selection without any new geometric-predicate code.
//
// Initial condition (paper's Sec. 4.3, Eq. (4.2)): u(0)=0, u_dot(0) = -w,
// where Delta w = 100 in Omega, w=0 on the boundary. In our first-order
// (v,p) = (grad u, u_dot) state this maps to: v(0)=0 (since u(0)=0), and
// p(0) = -w. w is obtained by a one-off HHO Poisson solve (same mesh, same
// hho_di) via acoustic_one_field_assembler + linear_solver, then injected as
// the acoustic-pressure initial condition through the existing
// project_over_cells/project_over_faces L2-projection API (same API already
// used for manufactured-solution ICs in ERK4_LTS_conv_test.hpp) via a
// callable wrapper that evaluates w at an arbitrary point (find_cells +
// pick_cell + local scalar-basis evaluation, the same idiom used in
// postprocessor.hpp's record_data_acoustic_one_field/compute_errors_one_field).
//
// Convergence check: since the first-order state never carries u itself,
// each coarse-mesh run's final-time PRESSURE field p (~ u_dot) is compared,
// via the same mass-matrix-weighted L2-projection technique used in
// postprocessor::compute_errors_one_field, against the finest ("reference")
// mesh's pressure field evaluated at the coarse mesh's own points -- the
// natural first-order analogue of the paper's L2/H1 error-vs-h study
// (Fig. 10), not numerically identical to it (different unknown, different
// discretization) but the same kind of optimal-order-on-a-graded-mesh claim.
//
// Usage example: ../../../wave_propagation -k1 -s0 -r0 -c0 -f1 -e0

void ERK4_LTS_Lshape_conv_test(int argc, char **argv);

// -----------------------------------------------------------------------
// Point-location + local scalar-basis evaluation, following the exact idiom
// of postprocessor.hpp's record_data_acoustic_one_field/_two_fields:
//   find_cells (nearest-vertex candidates) -> pick_cell (polygon test)
//   -> cell_basis.eval_functions(pt) . scalar_cell_dof
// -----------------------------------------------------------------------

// Layout: contiguous n_cbs scalar coefficients per cell (as produced by
// acoustic_one_field_assembler, e.g. the Poisson solve for w).
template<typename Mesh>
double evaluate_one_field_at_point(
    Mesh& msh, disk::hho_degree_info& hho_di,
    const Matrix<double, Dynamic, 1>& x_dof,
    typename Mesh::point_type pt)
{
    size_t n_cbs = disk::scalar_basis_size(hho_di.cell_degree(), Mesh::dimension);
    std::set<size_t> cell_indexes = postprocessor<Mesh>::find_cells(pt, msh, false);
    size_t cell_ind = postprocessor<Mesh>::pick_cell(pt, msh, cell_indexes, false);

    Matrix<double, Dynamic, 1> scalar_cell_dof = x_dof.block(cell_ind * n_cbs, 0, n_cbs, 1);
    auto& cell = msh.backend_storage()->surfaces[cell_ind];
    auto cell_basis = disk::make_scalar_monomial_basis(msh, cell, hho_di.cell_degree());
    auto t_phi = cell_basis.eval_functions(pt);
    return scalar_cell_dof.dot(t_phi);
}

// Layout: per acoustic cell, n_vec_dof flux coefficients followed by
// n_scal_dof pressure coefficients (elastoacoustic_four_fields_assembler's
// acoustic-cell block), matching postprocessor.hpp's
// record_data_acoustic_two_fields. Valid only when there are zero elastic
// cells (pure acoustic problem, as here), so the acoustic-cell block starts
// at global offset 0 and mesh cell index == acoustic cell position.
template<typename Mesh>
double evaluate_acoustic_pressure_at_point(
    Mesh& msh, disk::hho_degree_info& hho_di,
    const Matrix<double, Dynamic, 1>& x_dof,
    typename Mesh::point_type pt)
{
    size_t n_scal_dof = disk::scalar_basis_size(hho_di.cell_degree(), Mesh::dimension);
    size_t n_vec_dof  = disk::scalar_basis_size(hho_di.reconstruction_degree(), Mesh::dimension) - 1;
    size_t cell_dof   = n_scal_dof + n_vec_dof;

    std::set<size_t> cell_indexes = postprocessor<Mesh>::find_cells(pt, msh, false);
    size_t cell_ind = postprocessor<Mesh>::pick_cell(pt, msh, cell_indexes, false);

    Matrix<double, Dynamic, 1> scalar_cell_dof = x_dof.block(cell_ind * cell_dof + n_vec_dof, 0, n_scal_dof, 1);
    auto& cell = msh.backend_storage()->surfaces[cell_ind];
    auto cell_basis = disk::make_scalar_monomial_basis(msh, cell, hho_di.cell_degree());
    auto t_phi = cell_basis.eval_functions(pt);
    return scalar_cell_dof.dot(t_phi);
}

void ERK4_LTS_Lshape_conv_test(int argc, char **argv)
{
    std::cout << std::endl << bold << red << "   ERK4-LTS L-SHAPE GRADED MESH (reentrant corner)" << std::endl << std::endl;

    using RealType = double;
    simulation_data sim_data = preprocessor::process_args(argc, argv);
    sim_data.print_simulation_data();

    typedef disk::mesh<RealType, 2, disk::generic_mesh_storage<RealType, 2>>  mesh_type;
    typedef disk::BoundaryConditions<mesh_type, false> e_boundary_type;
    typedef disk::BoundaryConditions<mesh_type, true>  a_boundary_type;

    size_t cell_k_degree = sim_data.m_k_degree;
    if (sim_data.m_hdg_stabilization_Q) cell_k_degree++;
    disk::hho_degree_info hho_di(cell_k_degree, sim_data.m_k_degree);

    auto acoustic_mat_fun = [](const typename mesh_type::point_type&) -> acoustic_material_data<RealType> {
        return acoustic_material_data<RealType>(1.0, 1.0);
    };
    auto null_s_fun = [](const mesh_type::point_type&) -> double { return 0.0; };
    auto null_fun = [](const mesh_type::point_type&) -> disk::static_vector<double, 2> {
        disk::static_vector<double, 2> f{0, 0};
        return f;
    };
    auto null_flux_fun = [](const mesh_type::point_type&) -> disk::static_matrix<double, 2, 2> {
        return disk::static_matrix<double, 2, 2>::Zero(2, 2);
    };

    // -----------------------------------------------------------------
    // Mesh sequence: generated by generate_lshape_graded_mesh.py into
    // mesh_generation/lshape_graded/meshes/. Levels + reference (finest).
    // -----------------------------------------------------------------
    const std::string mesh_dir = "/home/mottie0000/Github/Diskpp/Disk/apps/wave_propagation/src/mesh_generation/lshape_graded/meshes/";
    // level_N/reference_N are convergence level indices ell: mesh files
    // "lshape_graded_k<k>_N<ell>.txt" couple a uniform background
    // refinement (ell times, halving h_max) with a FASTER corner-only
    // quadtree refinement (matching classical graded-mesh theory,
    // h_corner ~ h_max^{(k+1)/gamma}, gamma=2/3) -- see
    // generate_lshape_graded_mesh.py's module docstring for why an
    // uncoupled (background-fixed) corner-only refinement gives a
    // k-independent, capped observed order (~1.3 = 2*gamma) instead of the
    // true h^{k+1} rate. The mesh filename depends on sim_data.m_k_degree,
    // so the mesh files must be (re)generated for the k this is run with:
    //   python3 generate_lshape_graded_mesh.py --k <k> --levels ... --reference ...
    std::vector<int> level_N   = {0, 1};
    int reference_N            = 2;
    const size_t mesh_k        = sim_data.m_k_degree;

    std::vector<int> all_N = level_N;
    all_N.push_back(reference_N);

    struct level_result {
        int N;
        double h_max;
        double h_min;
        std::shared_ptr<mesh_type> msh;
        Matrix<RealType, Dynamic, 1> x_dof;
    };
    std::vector<level_result> results;

    for (int N : all_N) {

        bool is_reference = (N == reference_N);
        std::cout << bold << red << "\n   MESH LEVEL N=" << N << (is_reference ? "  (reference)" : "") << reset << std::endl;

        // ---------------- Mesh ----------------
        std::ostringstream mesh_fname;
        mesh_fname << mesh_dir << "lshape_graded_k" << mesh_k << "_N" << N << ".txt";

        auto msh_ptr = std::make_shared<mesh_type>();
        {
            polygon_2d_mesh_reader<RealType> mesh_builder;
            mesh_builder.set_poly_mesh_file(mesh_fname.str());
            mesh_builder.build_mesh();
            mesh_builder.move_to_mesh_storage(*msh_ptr);
        }
        mesh_type& msh = *msh_ptr;

        RealType h_max = 0.0, h_min = 1.0e10;
        for (auto & cell : msh) {
            RealType h_l = diameter(msh, cell);
            if (h_l > h_max) h_max = h_l;
            if (h_l < h_min) h_min = h_l;
        }
        int p = static_cast<int>(std::round(h_max / h_min));
        if (p < 1) p = 1;
        RealType h_c = (p == 1) ? 1.25 * h_max : 0.75 * h_max;

        std::cout << bold << cyan << "      n_cells=" << msh.cells_size()
                  << "  h_max=" << h_max << "  h_min=" << h_min
                  << "  p=" << p << reset << std::endl;

        // -----------------------------------------------------------------
        // Auxiliary elliptic HHO solve: Delta w = 100 in Omega, w=0 on dOmega
        // (same mesh, same hho_di as the wave problem below), following
        // EllipticOneFieldConvergenceTest.hpp's acoustic_one_field_assembler
        // + linear_solver pattern.
        // -----------------------------------------------------------------
        Matrix<RealType, Dynamic, 1> w_dof;
        {
            auto rhs_fun = [](const typename mesh_type::point_type&) -> RealType { return 100.0; };
            disk::BoundaryConditions<mesh_type, true> w_bnd(msh);
            w_bnd.addDirichletEverywhere(null_s_fun);

            auto w_assembler = acoustic_one_field_assembler<mesh_type>(msh, hho_di, w_bnd);
            acoustic_material_data<RealType> unit_material(1.0, 1.0);
            w_assembler.load_material_data(msh, unit_material);
            w_assembler.assemble(msh, rhs_fun);
            w_assembler.apply_bc(msh);

            linear_solver<RealType> w_analysis(w_assembler.LHS);
            w_analysis.factorize();
            w_dof = w_analysis.solve(w_assembler.RHS);
        }
        auto neg_w_fun = [&](const typename mesh_type::point_type& pt) -> RealType {
            return -evaluate_one_field_at_point(msh, hho_di, w_dof, pt);
        };

        // ---------------- Pure acoustic domain ----------------
        std::map<size_t, acoustic_material_data<RealType>> a_material;
        std::map<size_t, elastic_material_data<RealType>>  e_material;
        std::set<size_t> elastic_bc_face_indexes, acoustic_bc_face_indexes, interface_face_indexes;
        std::map<size_t, std::pair<size_t, size_t>> interface_cell_pair_indexes;

        for (auto & cell : msh) {
            auto cell_ind = msh.lookup(cell);
            a_material.insert(std::make_pair(cell_ind, acoustic_mat_fun(barycenter(msh, cell))));
        }

        size_t bc_elastic_id  = 0;
        size_t bc_acoustic_id = 1;
        for (auto face_it = msh.boundary_faces_begin(); face_it != msh.boundary_faces_end(); face_it++) {
            auto face  = *face_it;
            auto fc_id = msh.lookup(face);
            disk::boundary_descriptor bi{bc_acoustic_id, true};
            msh.backend_storage()->boundary_info.at(fc_id) = bi;
            acoustic_bc_face_indexes.insert(fc_id);
        }

        e_boundary_type e_bnd(msh);
        a_boundary_type a_bnd(msh);
        e_bnd.addDirichletBC(disk::DirichletType::DIRICHLET, bc_elastic_id,  null_fun);
        a_bnd.addDirichletBC(disk::DirichletType::DIRICHLET, bc_acoustic_id, null_s_fun);

        auto assembler = elastoacoustic_four_fields_assembler<mesh_type>(msh, hho_di, e_bnd, a_bnd, e_material, a_material);
        assembler.set_interface_cell_indexes(interface_cell_pair_indexes);
        assembler.set_coupling_stabilization();
        if (sim_data.m_scaled_stabilization_Q) assembler.set_scaled_stabilization();

        assembler.assemble_mass(msh);
        assembler.assemble_coupling_terms(msh);

        // ---------------- Initial condition: v(0)=0, p(0)=-w ----------------
        Matrix<RealType, Dynamic, 1> x_dof;
        assembler.project_over_cells(msh, x_dof, null_fun, null_flux_fun, neg_w_fun, null_fun);
        assembler.project_over_faces(msh, x_dof, null_fun, neg_w_fun);

        assembler.assemble(msh, null_fun, null_s_fun, true);
        assembler.LHS += assembler.COUPLING;

        std::set<size_t> elastic_internal_faces, acoustic_internal_faces;
        erk_coupling_hho_scheme<RealType> erk_an(assembler.LHS, assembler.RHS, assembler.MASS, assembler.COUPLING,
            assembler.get_e_n_cells_dof(), assembler.get_a_n_cells_dof(), assembler.get_e_face_dof(), assembler.get_a_face_dof());
        erk_an.Mcc_inverse(assembler.get_elastic_cells(), assembler.get_acoustic_cells(),
            assembler.get_e_cell_basis_data(), assembler.get_a_cell_basis_data());
        erk_an.Sff_inverse(assembler.get_elastic_faces(), assembler.get_acoustic_faces(),
            assembler.get_e_face_basis_data(), assembler.get_a_face_basis_data(),
            assembler.get_e_compress(), assembler.get_a_compress(),
            elastic_internal_faces, acoustic_internal_faces, interface_face_indexes);
        erk_an.refresh_faces_unknowns(x_dof);

        // nb_layer=3: a first-order mixed acoustic system (velocity+pressure,
        // no identity block) needs more buffer layers around the fine region
        // as the LTS ratio p grows -- exactly the structural point studied
        // all session in LTS_RK4/comparaison_ordre1_ordre2/ (a single buffer
        // layer sufficed for the toy chain model up to p=2048, but this is a
        // genuine 2D fan-topology mesh with many cells per "layer", not a
        // 1D chain, so more layers are used here for safety).
        assembler.assemble_P(msh, h_c, 3);

        // ---------------- Time discretization ----------------
        // dt must scale with h_max (the COARSE macro-step's own CFL limit),
        // not be fixed across levels: as N grows the graded mesh's coarse
        // region also shrinks (h_max decreases), so a dt stable at N=4 is
        // no longer stable at N=32 -- exactly the same CFL scaling already
        // used in ERK4_LTS_conv_test.hpp (nt scaled with refinement level).
        RealType ti = 0.0, tf = 0.05;
        const RealType cfl_factor = 0.002;
        RealType dt_target = cfl_factor * h_max;
        size_t nt = std::max<size_t>(1, static_cast<size_t>(std::round(tf / dt_target)));
        RealType dt = tf / nt;
        RealType dtau = dt / p;

        std::ostringstream fname;
        fname << "lshape_N_" << N << "_k_" << sim_data.m_k_degree << ".txt";
        std::ofstream simulation_log(fname.str());
        sim_data.write_simulation_data(simulation_log);
        simulation_log << "N=" << N << " n_cells=" << msh.cells_size()
                       << " h_max=" << h_max << " p=" << p
                       << " n_dof=" << x_dof.rows() << "\n";
        simulation_log.flush();

        Matrix<RealType, Dynamic, 1> F_zero = Matrix<RealType, Dynamic, 1>::Zero(x_dof.rows());

        for (size_t it = 1; it <= nt; it++) {

            auto x_dof_n = x_dof;

            std::vector<Matrix<RealType, Dynamic, 1>> w(4);
            for (int j = 0; j < 4; ++j) { w[j].resize(x_dof.rows()); w[j].setZero(); }

            erk_an.ZeroFc();
            if (p != 1) {
                erk_an.erk_weight_LTS_coarse(x_dof_n, assembler.Pcoarse, w, F_zero, F_zero, F_zero, dt);
            }
            for (int m = 0; m < p; m++) {
                RealType tm = m * dtau;
                erk_an.erk_weight_LTS_fine(x_dof_n, assembler.Pfine, w, F_zero, F_zero, F_zero, tm, dtau);
            }

            x_dof = x_dof_n;

            // Discrete energy diagnostic: 0.5 * x^T * MASS * x (conservation
            // check, analogous to the paper's Fig. 5).
            RealType energy = 0.5 * x_dof.dot(assembler.MASS * x_dof);
            simulation_log << "step=" << it << " t=" << ti + it*dt << " energy=" << std::setprecision(15) << energy << "\n";
        }
        simulation_log.close();
        std::cout << bold << cyan << "      --> " << fname.str() << reset << std::endl;

        if (sim_data.m_render_silo_files_Q) {
            std::ostringstream sn;
            sn << "silo_lshape_N_" << N << "_";
            postprocessor<mesh_type>::write_silo_four_fields_elastoacoustic_LTS(
                sn.str(), 0, msh, hho_di, x_dof, e_material, a_material, false, h_c, assembler.cell_is_fine_silo);
        }

        results.push_back(level_result{N, h_max, h_min, msh_ptr, x_dof});
    }

    // -----------------------------------------------------------------
    // Convergence check: L2 error of the final-time pressure field of each
    // coarser level vs the finest (reference) mesh, using the same
    // mass-matrix-weighted L2-projection technique as
    // postprocessor::compute_errors_one_field (project the reference field
    // onto each coarse cell's own basis, compare to the coarse DOFs there).
    // -----------------------------------------------------------------
    level_result& ref = results.back();
    std::ostringstream conv_fname;
    conv_fname << "lshape_convergence_k_" << sim_data.m_k_degree << ".txt";
    std::ofstream conv_log(conv_fname.str());
    conv_log << "# N  h_min  L2_error_pressure  h_max\n";

    std::cout << bold << red << "\n   CONVERGENCE (pressure L2 error vs reference N=" << ref.N << ")" << reset << std::endl;

    for (size_t li = 0; li + 1 < results.size(); ++li) {
        level_result& lvl = results[li];
        mesh_type& msh = *lvl.msh;

        size_t n_scal_dof = disk::scalar_basis_size(hho_di.cell_degree(), mesh_type::dimension);
        size_t n_vec_dof  = disk::scalar_basis_size(hho_di.reconstruction_degree(), mesh_type::dimension) - 1;
        size_t cell_dof   = n_scal_dof + n_vec_dof;

        RealType l2_error_sq = 0.0;
        size_t cell_i = 0;
        for (auto & cell : msh) {
            Matrix<RealType, Dynamic, 1> scalar_cell_dof = lvl.x_dof.block(cell_i * cell_dof + n_vec_dof, 0, n_scal_dof, 1);

            auto ref_fun = [&](const typename mesh_type::point_type& pt) -> RealType {
                return evaluate_acoustic_pressure_at_point(*ref.msh, hho_di, ref.x_dof, pt);
            };

            auto cell_basis = disk::make_scalar_monomial_basis(msh, cell, hho_di.cell_degree());
            Matrix<RealType, Dynamic, Dynamic> mass = make_mass_matrix(msh, cell, cell_basis, hho_di.cell_degree());
            Matrix<RealType, Dynamic, 1> rhs = make_rhs(msh, cell, cell_basis, ref_fun);
            Matrix<RealType, Dynamic, 1> proj_ref_dofs = mass.llt().solve(rhs);

            Matrix<RealType, Dynamic, 1> diff = proj_ref_dofs - scalar_cell_dof;
            l2_error_sq += diff.dot(mass * diff);
            cell_i++;
        }
        RealType l2_error = std::sqrt(l2_error_sq);

        std::cout << bold << cyan << "      N=" << lvl.N << "  h_min=" << lvl.h_min
                  << "  L2_error(pressure)=" << std::setprecision(10) << l2_error << reset << std::endl;
        conv_log << lvl.N << " " << std::setprecision(15) << lvl.h_min << " " << l2_error
                  << " " << lvl.h_max << "\n";
    }
    conv_log.close();
    std::cout << bold << red << "\n   --> " << conv_fname.str() << reset << std::endl << std::endl;
}
